### ISSUE TITLE
In advanced JSON some of the actions aren't executed, for example the hideButtons action

### ISSUE THREAD

**Issue by compubasejovl** [foex-open-source/fos-execute-plsql-code#2]
When returning the advanced JSON some of the actions aren't executed.

In the example JSON I see that I can hide buttons by adding ""hideButtons": ["BUTTON1","BUTTON2"]," to my JSON response. 
The problem is it doesn't work.

I have looked to the JS file "script.js" and found the function "_performActions" and the action "hideButtons" isn't in there.

**Comment by foex-open-source** [comment]
Hi, thanks for letting us know, it seems we missed those during testing. We are fixing this in development and we will provide an update in the near future.

**Comment by foex-open-source** [comment]
Fixed in the new Release v20.1.1
