### ISSUE TITLE
Popup LOV - support

### ISSUE THREAD

**Issue by glebovpavel** [foex-open-source/fos-execute-plsql-code#3]
"Popup LOV" is now a standard input type in APEX, to replace an old Select List. But using of this item has some difficulties, which can be fixed using this plugin.

By default developer should set display value of Popup LOV-Item manually, when the value is returned using Execute Pl/SQL Dynamic Action or Excute PL-SQL plugin.
Workaround is mentioned on https://community.oracle.com/thread/4274006
the Idea is to  fill display value completely automatically, without any care. Plugin can detects all Popup LOV's mentioned in return items, automatically get display values and set it to the items on the page.

One can also take a working code from 
https://github.com/apexutils/Execute-PL-SQL-Code/pull/2

**Comment by foex-open-source** [comment]
Thanks Pavel, it's a great idea! We have looked at your pull request and will include this enhancement in the next FOS release.

**Comment by stefandobre** [comment]
The enhancement has been included in FOS version 20.2 which you can download from [here](https://fos.world/).

See the advanced usage section on the Execute PL/SQL Code demo page.

Thanks for the suggestion!
