### ISSUE TITLE
Function get_display_value throws exception Item P0_xyz not found

### ISSUE THREAD

**Issue by mbrde** [foex-open-source/fos-execute-plsql-code#4]
Return Item Value to P0 Items does not work since the last Update.

**Comment by mbrde** [comment]
solution:
..
l_page_id          apex_application_page_items.page_id%TYPE := nv('APP_PAGE_ID');
l_app_id           apex_application_page_items.application_id%TYPE := nv('APP_ID');
..
WHERE application_id = l_app_id AND page_id IN (0, l_page_id)
..

**Comment by mnolan866** [comment]
Thanks, we'll make the required fix as per your suggestion and include it in the next release. For everyone following this, just update the plug-in directly yourself. e.g.

![image](https://user-images.githubusercontent.com/63710026/107030830-e1cf4500-67b9-11eb-865d-1f7f7f393c0b.png)

**Comment by foex-open-source** [comment]
Fixed in just published v21.1.0
