### ISSUE TITLE
Should this work for radio buttons?

### ISSUE THREAD

**Issue by joeph** [foex-open-source/fos-execute-plsql-code#5]
I noticed that radio buttons are not updated.
Is this a missing feature?

**Comment by mnolan866** [comment]
This sounds like a bug. Are you able to provide a test case on apex.oracle.com which we could look at to see what your setup looks like?

**Comment by joeph** [comment]
Thanks for your quick reply!

Not a bug in the plugin, more likely an Oracle bug.
We have defined an OUT-parameter of type char. Oracle adds spaces to a length of 4000 to the out parameter.
I am not sure if this an oracle feature or a bug ;-)
We will change our outparams to varchar2.
